# Generated by Django 5.2.5 on 2025-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
