# Generated by Django 5.2.5 on 2025-08-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
