# Generated by Django 5.2.5 on 2025-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_address_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
